### ISSUE TITLE
Explicitly set HTTPMode should not be overridden

### ISSUE THREAD

**Issue by reeset** [dotnetrdf/dotnetrdf#128] opened 2017-10-21 16:13 UTC
I'm using the following sample code:
`SparqlRemoteEndpoint endpoint = new SparqlRemoteEndpoint(new Uri(@"http://id.ndl.go.jp/auth/ndla"));                
endpoint.HttpMode = "GET";             
 SparqlResultSet results = endpoint.QueryWithResultSet(textBox1.Text);               
 `
in the Textbox, I have the following sparql query:

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xl: <http://www.w3.org/2008/05/skos-xl#>
SELECT ?subj WHERE { 
 {?subj rdfs:label ?heading} UNION
 {?subj xl:altLabel [ xl:literalForm ?heading]}
 filter (?heading = "軍事基地")
 }

The problem appears to be the Japanese characters.  If I change them to English, I can control the HTTPMode and set either Get or Post.  If I include the Japanese characters, it only posts and my query fails, as the service doesn't response to post requests with anything but HTML.  This doesn't appear to be the expected behavior? 

I'm using the 2.0 pre-release 8.

**Comment by kal** [comment] 2017-10-23 10:32
This isn't expected behavior but it may be related to trying to encode the URL parameter. 
I'll take a look...thanks for the report!

**Comment by kal** [comment] 2017-10-23 11:11
Yes, it looks like the use of non-ascii characters forces the query into POST mode because of this line in SPARQLRemoteEndpoint.cs (line 451):

`            if (!this.HttpMode.Equals("POST") && sparqlQuery.Length <= LongQueryLength && sparqlQuery.IsAscii())
`

All the above conditions have to be true to honor the `HttpMode` setting. So it is the Japanese characters that are causing it to switch to POST.

IMO this behavior probably should be changed so that an explicitly set `HttpMode` is always honored (even if it means creating long request URIs). If the `HttpMode` is not explicitly set then I think it is fine for us to switch between GET and POST based on our own (documented?) heuristics, but if the developer explicitly chooses a mode, then we should use that mode even if it breaks stuff :-)

Fortunately the 2.0 release means that we can make this potentially breaking change now.

**Comment by reeset** [comment] 2017-10-25 21:36
Thanks for the explanation.  Being able to explicitly set this would be great.  In the user space I'm working in, I've finding many endpoints only support GET, regardless of how long the URLs are -- so letting the developer explicitly set this mode would be great.

Thanks

**Comment by kal** [comment] 2017-11-03 15:25
This is now fixed in PR #132

**Closed by kal** 2017-11-03 15:25 UTC
