### ISSUE TITLE
VirtuosoManager.UpdateGraph not successful with Virtuoso server

### ISSUE THREAD

**Issue by fschumac** [dotnetrdf/dotnetrdf#390] opened 2021-04-28 09:46 UTC
Hey folks,

I have a Virtuoso-Server on a linux machine (I "inherited" it, so I did not set it up myself). I also inherited the OntoWiki frontend connected to the server to manipulate the data. As this is a bit clumsy and very manual, I wrote a C# project to access and display the data. I access the data using dotNetRdf. Reading is no problem, but now I also want to update the data, thus using the UpdateGraph method. To test this, I wrote a small test-project, after this example from your website: https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Triple-Store-Integration#updategraph

This is my implementation.

```
VirtuosoManager _virtuosoManager = new VirtuosoManager(ServerAddress, ServerPort, VirtuosoManager.DefaultDB, _user, _password);
string _graphName = "http://od.fmi.uni-leipzig.de/example";

Graph _graph = new Graph();
_virtuosoManager.LoadGraph(_graph, _graphName);

INode s = _graph.CreateUriNode(new Uri(_graphName + "/test"));
INode p = _graph.CreateUriNode(new Uri(RdfSpecsHelper.RdfType));
INode o = _graph.CreateUriNode(new Uri("http://example.org/Example"));
Triple t = new Triple(s, p, o);

_virtuosoManager.UpdateGraph(_graphName, new List<Triple>() { t }, null);
```
This code runs with no error, but alas also without any update in the graph (which I check with the follwing SPARQL-Request)

```
SELECT * WHERE {GRAPH ?g {<http://od.fmi.uni-leipzig.de/example/test> ?p ?o .}}
```
which returns nothing.

But when I use the Update method, the triple is inserted to the database:

```
string query = "INSERT DATA " + Environment.NewLine +
               "INTO <http://od.fmi.uni-leipzig.de/example>" + Environment.NewLine +
               "{" + Environment.NewLine +
                 "<http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> ." + Environment.NewLine +
               "}";

_virtuosoManager.Update(query);
```

Have you any idea what might go wrong with the UpdateGraph-Method? Is there any other way to transform a triple to an Insert/Delete query than to manually code it myself (I'm a bit afraid of edge cases and issues I am not aware of).

Thanks in advance,
Frank

PS: I hope this is the right place to ask the question. I already asked at Stackoverflow (https://stackoverflow.com/questions/67280293/dontnetrdf-method-updategraph-not-successful-with-virtuoso-server), where a user pointed me to this page

**Comment by fschumac** [comment] 2021-04-28 11:56
This is the server log from the UpdateGraph-Request

```
15:47:16 CSLQ_0 109 xxx.xxx.xxx.xxx 1113:2 s1113_2_1 SPARQL define output:format '_JAVA_' INSERT DATA
INTO <http://od.fmi.uni-leipzig.de/example>
{
  <http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}

15:47:16 COMP_2 109 xxx.xxx.xxx.xxx 1113:2 Compile text:  SPARQL define output:format '_JAVA_' INSERT 
DATA
INTO <http://od.fmi.uni-leipzig.de/example>
{
  <http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}

15:47:16 EXEC_1 109 xxx.xxx.xxx.xxx 1113:2 s1113_2_1 Exec 1 time(s) SPARQL define output:format 
'_JAVA_' INSERT DATA
 INTO <http://od.fmi.uni-leipzig.de/example>
{
  <http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}
```
and this from the Update-Request

```
13:45:58 CSLQ_0 109 xxx.xxx.xxx.xxx 1113:2 s1113_2_0 SPARQL INSERT DATA 
INTO <http://od.fmi.uni-leipzig.de/example>
{
<http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}
13:45:58 COMP_2 109 xxx.xxx.xxx.xxx 1113:2 Compile text:  SPARQL INSERT DATA 
INTO <http://od.fmi.uni-leipzig.de/example>
{
<http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}
13:45:58 EXEC_1 109 xxx.xxx.xxx.xxx 1113:2 s1113_2_0 Exec 1 time(s) SPARQL INSERT DATA 
INTO <http://od.fmi.uni-leipzig.de/example>
{
<http://od.fmi.uni-leipzig.de/example/test> a <http://example.org/Example> .
}
```

As you can see, the difference is the 

> define output:format '_JAVA_'

in the UpdateGraph-Method call result, which could be the reason for the problem?

**Comment by kal** [comment] 2021-05-01 12:41
Hi Frank,

Sorry for the delay in replying!

The output:format isn't the problem here I think. The issue is that the update transaction is not committed by the code as you have it. The way to do this is to call the Dispose() method on _virtuosoManager. So wrapping your update in a using() block is the best way to go:

```c#
using(var _virtuosoManager = new VirtuosoManager(...)) {
 // Call one or more update methods
}
```

Or alternatively you can explicitly call Dispose() (for example if you are going to wrap the manager instance in another class).

Hope that helps and fixes the issue for you. If not please feel free to reopen this ticket!

**Closed by kal** 2021-05-01 12:41 UTC
Labels: question

**Comment by fschumac** [comment] 2021-05-04 10:51
Hey Kal,

thank you very much for the reply, it indeed solved my problem! (I used .Dispose()) Although I probably need to change my implementation logic. I made a connection to Virtuoso on program start and then used that connection for accessing Virtuoso until the end of the program. Looks now I need to re-initialize the connection for each access (read and write)? Is that supposed to be that way? 
And if so, maybe you could update the example at https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Triple-Store-Integration#updategraph because there is neither a using or a Dispose().

Thanks again for you help, it is much appreciated. DotNetRdf is helping me big time with the dealing with rdf data <3

**Comment by kal** [comment] 2021-05-04 19:22
Hi Frank,

I think it is a bit strange that the Virtuoso provider is implemented that way - it doesn't implement the ITransactionalStorage interface which would give you control over starting, committing and rolling back a transaction. I think that this is something that we probably should consider (and while there, change the semantics of the operations such that they auto-commit if there is no open transaction). All of those changes would potentially break existing code using the provider so I think this would have to be a 3.0 update, but it feels like it would be worth doing. I'm going to create a separate ticket for that.

I'll add a note to the docs about the triple stores that points out this odd behaviour of the Virtuoso provider (I think adding it to the example could be misleading because it is the only provider that needs to be used in this way...)

**Comment by fschumac** [comment] 2021-05-06 08:08
Hi Kal,

yes, this sounds quite reasonable and from my tests it works with creating and disposing the Manager for each operation, even if it is a bit odd. I wonder how many people are using the VirtuosoManager, as I didn't came along any answer regarding the not-commiting issue, but maybe all of them are using the using statement?
Anyways, thanks again for taking on that issue and I am looking forward to see 3.0 :)
