### ISSUE TITLE
Godot: difficulty reading JSON-LD from a URL

### ISSUE THREAD

**Issue by calummackervoy** [dotnetrdf/dotnetrdf#484] opened 2022-06-04 20:14 UTC
# Environment

I'm using version `2.7.4` of dotNetRdf, .NET framework `4.7.2`, Core SDK `6.0` (latest versions) but the `.csproj` configured SDK is `Godot.NET.Sdk/3.3.0` (I tested and this is necessary) - I believe it leverages the .NET Core SDK somewhere because it's in the install instructions (I can ask the Godot developers about the relationship)

# Steps to reproduce

I've set up a simple Flask server with the following endpoint:

```python
@app.route("/get-static-demo-map/")
def get_static_demo_map():

    data = {
        "@context": {
            "map": {
                "@id": "http://xmlns.com/foaf/0.1/map",
                "@container": "@list"
            }
        },
        "@id": "http://example.org/people#joebob",
        "map": [
            [0,0,0],
            [0,0,0]
        ],
        "https://raw.githubusercontent.com/Multi-User-Domain/vocab/main/mudworld.ttl#Region": {
            "http://xmlns.com/foaf/0.1/name": "Attica"
        }
    }

    return jsonify(data), 200, {'Content-Type': 'application/ld+json'}
```

Note that the data here is using a JSON-LD 1.1 feature (the multi-dimensional list), but the bug can also be reproduced removing that property/context

In my Godot C# script, I ran the following code:

```
IGraph g = new Graph();
UriLoader.Load(g, new Uri("http://localhost:5000/get-static-demo-map/"));

// raises Exception "The Library does not contain any Parsers for RDF Graphs in any of the following MIME Types: application/ld+json"
```

# Expected behaviour

I believe that the `JsonLdParser` should be selected

# Other suggestions

In the documentation ([here](https://dotnetrdf.org/docs/2.7.x/user_guide/Reading-RDF.html#reading-rdf-from-uris)) where it reads:

> The UriLoader will automatically select the correct Parser to use based on the returned Content-Type header of the HTTP Response

it would have been useful to have a mapping between content-type and parser because this would eliminate whether it was a bug or if I had done something wrong

**Comment by calummackervoy** [comment] 2022-06-04 20:21
Reposting here for reference but I did find a way to read the data using a `TripleStore` in place of a `Graph`: https://github.com/dotnetrdf/dotnetrdf/discussions/483#discussioncomment-2884285

**Comment by kal** [comment] 2022-06-05 13:31
Thanks for the report. The reason that you are seeing this behaviour is that JSON-LD is a quad format that supports having triples in multiple separate graphs and so the parser implements the `IStoreReader` interface rather than the `IRdfReader` interface. I can see how this is non-obvious because of the two overloads that `UriLoader` provides and so it should be clearly documented somewhere as a minimum. Having a list of which formats are supported, along with the recognised media type(s), and whether they require a TripleStore as the target would be a good start. We could maybe also think of ways to support "down-parsing" quad formats into a single graph - though there are different options here and it might end up being just as confusing if the library applies some default processing. I'm going to close this one as the specific issue is actually expected behaviour, but I'll open separate tickets for the documentation suggestion and for the possibility of adding some options to the new `Loader` interface that replaces `UriLoader` in the upcoming 3.0 release.

**Closed by kal** 2022-06-05 13:31 UTC
