### ISSUE TITLE
[Docs] Reading RQF from URI example throws exception (303)

### ISSUE THREAD

**Issue by kojo12228** [dotnetrdf/dotnetrdf#518] opened 2022-09-20 16:24 UTC
The following example from the docs throws an exception relating to status code 303:

https://github.com/dotnetrdf/dotnetrdf/blob/41a5ece1be51d03c46500def1fde3e12c5db1043/docs/user_guide/reading_rdf.md?plain=1#L91-L97

Exact code I ran:

```fsharp
open System.IO
open VDS.RDF
open VDS.RDF.Parsing

let barackObamaGraph = new Graph()
let loader = Loader()
loader.LoadGraph(barackObamaGraph, new Uri("http://dbpedia.org/resource/Barack_Obama"))
```

Which gives the following exception:

```
Error: System.AggregateException: One or more errors occurred. (Failed to load from the URI 'http://dbpedia.org/resource/Barack_Obama'. Server reports status 303: See Other.)
 ---> VDS.RDF.RdfException: Failed to load from the URI 'http://dbpedia.org/resource/Barack_Obama'. Server reports status 303: See Other.
   at VDS.RDF.Parsing.Loader.AssertResponseSuccess(Uri uri, HttpResponseMessage httpResponse)
   at VDS.RDF.Parsing.Loader.LoadGraphAsync(IRdfHandler handler, Uri uri, IRdfReader parser, CancellationToken cancellationToken)
   at VDS.RDF.Parsing.Loader.LoadGraphAsync(IGraph graph, Uri uri, IRdfReader parser, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at VDS.RDF.Parsing.Loader.LoadGraph(IGraph graph, Uri uri, IRdfReader parser)
   at VDS.RDF.Parsing.Loader.LoadGraph(IGraph graph, Uri uri)
   at <StartupCode$FSI_0016>.$FSI_0016.main@()
```

If I instead change to a specific format, this did work:

```fsharp
let barackObamaGraph = new Graph()
let loader = Loader()
loader.LoadGraph(barackObamaGraph, new Uri("http://dbpedia.org/data/Barack_Obama.ttl"))
```

- Should the example code be able to handle redirection?
- How do I configure the library to handle redirection (I've only started reading the docs, I expect it might be handled later)?

**Comment by kal** [comment] 2023-03-12 13:12
The redirect *should* be handled by HttpClient. I'm not sure why it is not in this case. 

There is a redirect from HTTP to HTTPS - if you follow the redirects in curl you see a redirect from  http://dbpedia.org/resource/Barack_Obama to https://dbpedia.org/resource/Barack_Obama and then to https://dbpedia.org/data/Barack_Obama.jrdf (the data URL will depend on what Accept: header you send in the request). 

From the .NET docs [here](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=net-7.0#system-net-http-httpclienthandler-allowautoredirect) it seems to me that a redirect from HTTP to HTTPS *should* be being followed by the default `HttpClient` instance that `Loader` uses, but that doesn't happen in this example.  Even if I try to explicitly set this by creating a new `HttpClient` with an `HttpClientHandler` with `AllowAutoRedirect` set to `true`, I still get the problem you report with the DBPedia endpoint. I also get the same problem if I use https://dbpedia.org/resource/Barack_Obama as the initial URL to load from (so that transition from HTTP to HTTPS doesn't seem to be the root cause of the problem).

I think the only fix for this is to implement some additional redirect handling code in the Loader class itself. This would be in addition to the HttpClient redirect handling so if you wanted to disable all redirect following for the Loader you would have two places you need to go to turn it off, but that feels like a minor inconvenience in comparison to not having a Loader that "just works" out of the box regardless of redirects that the server sends.

**Closed** 2023-03-12 14:16 UTC
Labels: documentation
